fixtures:
  repositories:
    cron:
      repo: 'https://github.com/puppetlabs/puppetlabs-cron_core.git'
    inifile:
      repo: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    puppet: "#{source_dir}"
